version: "3.8"

services:
  backend:
    build: services/backend
    environment:
      PORT: 3002
      ROUTE_BASE: '/api'
      BASE_URL: http://localhost:3002/api
      OIDC_ISSUER_BASEURL: https://prioratus.eu.auth0.com
      OIDC_AUTH_SECRET: ${OIDC_AUTH_SECRET}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
    ports:
      - 3002:3002
  frontend:
    build: services/frontend
    ports:
      - 3003:80
