version: "3.8"

services:
  backend:
    build: backend
    environment:
      PORT: 80
      ROUTE_BASE: '/api'
      BASE_URL: http://localhost:3002/api
      FRONTEND_RECIRECT_URL: http://localhost:3000/
      OIDC_ISSUER_BASEURL: https://prioratus.eu.auth0.com
      OIDC_AUTH_SECRET: ${OIDC_AUTH_SECRET}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      DATABASE_URL: postgresql://postgres:n6uHLuSK9vs9fnutd6Yc3MTU3NAYte6KTrQ@db:5432/postgres?schema=public
    ports:
      - 3002:80
    depends_on:
      - db

  frontend:
    build: frontend
    ports:
      - 3000:80

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: n6uHLuSK9vs9fnutd6Yc3MTU3NAYte6KTrQ
    volumes:
      - dbpgdata:/var/lib/postgresql/data

  migrate:
    build: backend
    entrypoint: npx prisma migrate
    command: specify your own
    volumes:
      - ./backend/prisma:/app/prisma
    environment:
      DATABASE_URL: postgresql://postgres:n6uHLuSK9vs9fnutd6Yc3MTU3NAYte6KTrQ@db:5432/postgres?schema=public
    depends_on:
      - db

volumes:
  dbpgdata:
