@startuml domain model
left to right direction

class User << auth0 >> {
    +id: UUID
    +displayName: string
    +email: string
    +createdDate: Date
}

class UserConfig << yaml >> {
    +email: string
    +timeZone: TZstring
    +horas: Hora
}
UserConfig "+email" --- "+email" User

class Hora << yaml >> {
    time
}

@enduml