@startuml usecases
left to right direction
skinparam packageStyle rectangle

usecase "Talk on chat" as UCTalkChat
UCTalkChat <|-- (On FB Messenger)
UCTalkChat <|-- (On Telegram)

usecase "Receive notifications of liturgia horarum prayers" as UCReceive
UCReceive <-. UCTalkChat :include
:User: <-- UCReceive
:User: --> (Create account on website)
usecase "Create account by chat" as UCAccountChat
UCAccountChat <-. UCTalkChat :include
:User: --> UCAccountChat
usecase UCConnectAccounts as "Connect website account 
to chat account and vice-versa"
:User: --> UCConnectAccounts
usecase UCConfigureLOH as "Configure liturgy of hours
reminders on the website" 
:User: --> UCConfigureLOH
UCConfigureLOH .-> (Login to website using link from chat) :include
@enduml
