@startuml usecases
left to right direction

skinparam usecase {
    BackgroundColor<< Done >> LightGreen
    BackgroundColor<< Wip >> LightBlue
}

usecase "Talk on chat" as UCTalkChat
usecase UCChatMessenger as "On FB Messenger"
UCTalkChat <|-- UCChatMessenger
usecase UCChatTelegram as "On Telegram" << Wip >>
UCTalkChat <|-- UCChatTelegram

usecase "Receive notifications of liturgia horarum prayers" as UCReceive
UCReceive <-. UCTalkChat :include
:User: <-- UCReceive
usecase UCCreateAccountWebsite as "Create account on website" << Done >>
:User: --> UCCreateAccountWebsite
usecase "Create account by chat" as UCAccountChat << Wip >>
UCAccountChat <-. UCTalkChat :include
:User: --> UCAccountChat
usecase UCConnectAccounts as "Connect website account 
to chat account and vice-versa"
:User: --> UCConnectAccounts
usecase UCConfigureLOH as "Configure liturgy of hours
reminders on the website" 
:User: --> UCConfigureLOH
UCConfigureLOH .-> (Login to website using link from chat) :include
@enduml
