apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prioratus-ingress
spec:
  rules:
    - host: katedra2.jblew.pl
      http:
        paths:
          - path: /prioratus
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80