apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prioratus-ingress
spec:
  rules:
    - host: przeor.jblewandowski.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
    - host: prioratus.jblewandowski.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80